version: '2'


services:
  web:
    build:
      context: .
      dockerfile: Docker
    container_name: web
    ports:
      - "42000:6000"
  db:
    image: mongo:3.6.1
    container_name: db
    volumes:
      - mongodb:/data/db
      - mongodb_config:/data/configdb
    ports:
      - 27017:27017
    command: mongod
  log1:
    build:
      context: .
      dockerfile: DockerLog
    container_name: LogService1
    ports:
      - "35001:6000"
  log2:
    build:
      context: .
      dockerfile: DockerLog
    container_name: LogService2
    ports:
      - "35002:6000"
  log3:
    build:
      context: .
      dockerfile: DockerLog
    container_name: LogService3
    ports:
      - "35003:6000"

volumes:
  mongodb:
  mongodb_config: